# Generated by Django 2.2.5 on 2019-11-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='medium',
            field=models.CharField(default='medium', max_length=100),
        ),
    ]
