# Generated by Django 2.2.5 on 2019-11-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_medium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='medium',
            field=models.CharField(max_length=100),
        ),
    ]
