# Generated by Django 2.2.5 on 2019-11-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20191126_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='medium',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
